### ISSUE TITLE
No Opengraph or Google Jobs Data

### ISSUE THREAD

**Issue by schorsch8878** [typo3-itx/jobapplications#1]
Hello, I set the constant google data to 1 and set a Company Name in the Extension Configuration but there are no Google Jobs Data in the html Code.

**Comment by typo3-itx** [comment]
Hi,
thanks for reaching out!

We can't seem to find a problem with the Google Jobs data generation on our end.

Have you made sure that you have set the correct key via Typoscript (plugin.tx_jobapplications.settings.enableGoogleJobs) OR via the template constant editor.
The Google Jobs data will be present in the <head> section inside a <script type="application/ld+json"> tag, when the feature is activated.

Also the Opengraph tags are independent from Google Jobs as they are output via a template partial called MetaTags.html.

Hope we could help!

**Comment by schorsch8878** [comment]
Thanks for your answer. I checked all and set the Constants in another .ts file auf my distribution. No it works!! Your Extension is very fine! Viele Grüße!

**Comment by typo3-itx** [comment]
Glad we could help and thank you very much!
