### ISSUE TITLE
Translate TCA Fields

### ISSUE THREAD

**Issue by der-phillip** [typo3-itx/jobapplications#10]
Hello,

how can I translate the fields or add my own fields?

https://github.com/typo3-itx/jobapplications/blob/1a144dce09acb3657a5081c89479c7fda295ce7f/Configuration/TCA/tx_jobapplications_domain_model_posting.php#L173

**Comment by typo3-itx** [comment]
Hi,
these fields aren't actually meant to be modified, as they correlate exactly to the Google Jobs fields. You might have to find another solution.
