### ISSUE TITLE
Issues - No created record & "Sorry, the requested view was not found."

### ISSUE THREAD

**Issue by misterbond007** [typo3-itx/jobapplications#11]
Hi there!

I've successfully installed the extension. I have made it until the application form. When I wanna send the entered data at the application form website, the page is being reloaded again with the application form without any data entered. It should be loaded the "Success" page and the data should be written into the MySQL table. No records are written to the MySQL table. I've set the success page link in the plugin section of the application form.

Also, after clicking the "Application" Typo3 navigation button, it says "Sorry, the requested view was not found. The technical reason is: No template was found. View could not be resolved for action "dashboard" in class "ITX\Jobapplications\Controller\BackendController"."

**Comment by misterbond007** [comment]
Situation, that the form is not being send, only if a text is entered at "Message".

**Comment by typo3-itx** [comment]
Hi, it looks like there is a bug in the Application Template, where the Message Field visibility doesn't correspond to the plugin setting. You can workaround this, by either activating the field in the plugin settings and set a max character setting OR removing the field from the template.

The unwanted redirect is a security measure against spam, checking if the max char value in plugin settings is kept in bounds in the actual application message.

**Comment by typo3-itx** [comment]
The other Issue with the Backend Module sounds like missing static template includes. Have you made sure that the static template is included?

**Comment by misterbond007** [comment]
Ok, thank you. How can I activate the message field in the plugin settings and set a max character setting?

**Comment by misterbond007** [comment]
The other issue was solved with inluding the static template in the root TYPO3 template of the website.

**Comment by typo3-itx** [comment]
Good to hear! You can activate the field by going into the settings of the application form plugin and activate the 'Show "Message" field' Checkbox
