### ISSUE TITLE
Slug-Configuration

### ISSUE THREAD

**Issue by der-phillip** [typo3-itx/jobapplications#14]
Is there a slug configuration for the extension?

**Comment by typo3-itx** [comment]
Do you mean RouteEnhancers? There is an example for this in Configuration/Routes/Default.yaml

**Comment by der-phillip** [comment]
Yes, only I now land on the details page on a 404 error page.

**Comment by typo3-itx** [comment]
Interesting, that shouldn't happen. But I don't think I can help you, as I don't know the specific circumstances of your installation. All I can tell you is to take the example config and modify it to your needs.
