### ISSUE TITLE
View could not be resolved for action "dashboard" in class ITX\Jobapplications\Controller\BackendController

### ISSUE THREAD

**Issue by SirFulgeruL** [typo3-itx/jobapplications#15]
Hello, when I try to access the dashboard from backend panel, it outputs the error:

`Sorry, the requested view was not found. The technical reason is: No template was found. View could not be resolved for action "dashboard" in class "ITX\Jobapplications\Controller\BackendController".`

My Typo3 version is: 10.4.6

**Comment by typo3-itx** [comment]
Please make sure to include the static template of the extension. Thats a common problem fix.
