### ISSUE TITLE
Exception error when submitting the application for

### ISSUE THREAD

**Issue by der-phillip** [typo3-itx/jobapplications#3]
I receive an exception error when submitting the application form.

> PHP Warning: count(): Parameter must be an array or an object that implements Countable in /html/typo3/typo3conf/ext/jobapplications/Classes/Controller/ApplicationController.php line 239

> at TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'count(): Parameter must be an array or an object that implements Countable', '/html/typo3/typo3conf/ext/jobapplications/Classes/Controller/ApplicationController.php', 239, array('newApplication' => object(ITX\Jobapplications\Domain\Model\Application), 'posting' => object(ITX\Jobapplications\Domain\Model\Posting), 'allowedFileTypes' => array('application/pdf')))

**Comment by typo3-itx** [comment]
Hi,
thanks for reporting a potential bug! We will check both of your issues and get back to you on monday.

**Comment by typo3-itx** [comment]
Hello again,
we could not reproduce this particular issue, but have take measures to catch this so no error should show up and it should work normally. We have released a new version with this particular fix. Please check and let us know if something is still not working.

**Comment by der-phillip** [comment]
Fixed. Thank you.
