### ISSUE TITLE
Error trying to send crawl request to Google

### ISSUE THREAD

**Issue by der-phillip** [typo3-itx/jobapplications#4]
After saving a job posting, I get the following error message. Where can the setup error be?

`{ "error": { "code": 400, "message": "Invalid attribute. 'url' is not in standard URL format: www.mydomain.com/index.php?id=280&tx_jobapplications_detailview[action]=show&tx_jobapplications_detailview[controller]=Posting&tx_jobapplications_detailview[posting]=2", "status": "INVALID_ARGUMENT" } }`

**Comment by typo3-itx** [comment]
Thanks for reporting this particular bug.

There seemed to be an issue with the url generation resulting in the url not beginning with 'https//:'. We have released a new version including a fix for this.
Please let us know if you still encounter problems with this.

**Comment by der-phillip** [comment]
Hello, I'm using vhs 6.0.0. I hope that's not the problem? Your extension is only until 5.9.9. released.

After Update the Error is:
`{ "error": { "code": 403, "message": "Permission denied. Failed to verify the URL ownership.", "status": "PERMISSION_DENIED" } }`

**Comment by typo3-itx** [comment]
That shouldn't be a problem as vhs is only really used for meta tags generation.

This Error is actually good because it means the request was successfully delivered, but now you have to make sure that google knows that this is your domain see [Verify site ownership](https://developers.google.com/search/apis/indexing-api/v3/prereqs#verify-site)

**Comment by der-phillip** [comment]
I have made. Nevertheless, the instructions are out of date and I have added the use as an unrestricted user.

**Comment by typo3-itx** [comment]
This is an issue where you might need to contact Google. There is a [Stackoverflow ](https://stackoverflow.com/questions/60553749/google-indexing-api-permission-denied-failed-to-verify-the-url-ownership) posting though which describes the problem you are having. Maybe it helps. 

Closing the issue for now.
