### ISSUE TITLE
html Code in Mail

### ISSUE THREAD

**Issue by schorsch8878** [typo3-itx/jobapplications#5]
Hello, in the Success Email Mac Mail shows html Code (br) (p) I could not find a Template for the Email. Where is the Error? 

Many Thanks

**Comment by typo3-itx** [comment]
Hi,
there is no template in the TYPO3 9 version , the email gets generated by the controller.
Which extension version are you using? And what do you mean by "Email Mac Mail"; does this problem only occur on Mac?

**Comment by schorsch8878** [comment]
Hello, we use the Version 0.9.5. Nope the Problem is in every emailclient
![Bildschirmfoto 2020-04-27 um 13 55 10](https://user-images.githubusercontent.com/26795388/80371803-c8948200-8892-11ea-8a13-27b3b54ade4f.png)
. Look In the Attachement for example. Thank you

**Comment by typo3-itx** [comment]
Thanks for reporting this. We could only reproduce this partially. The error was the emails not being sent with html headers. This will be fixed in the next update, which is coming soon.

**Comment by schorsch8878** [comment]
Hello, many thanks! The New Version fixed the Problem successfully!
