### ISSUE TITLE
Error with hiringOrganization logo

### ISSUE THREAD

**Issue by derghostface** [typo3-itx/jobapplications#6]
If you define a logo for the hiringOrganization, the json becomes invalid because a new property hiringOranization (see the misspelling, missing "g") will be added.

Line 226 in PostingController.php should be changed to:
`$hiringOranization["logo"] = $logo;`

The misspelling of hiringOranization is also in the variable name.

**Comment by typo3-itx** [comment]
Indeed there is. Thank you very much for pointing that out!
It will be fixed in the next version!

**Comment by derghostface** [comment]
Unfortunately this fixes only the misspelling, but now you have a subproperty "hiringOrganization" in the property "hiringOrganization":
```
hiringOrganization": {
  "@type": "Organization",
  "name": "Foobar",
  "hiringOrganization": {
    "logo": "https:\/\/www.domain.de\/logo.png"
  }
}
```

The correct fix in line 226 is the one in my first comment (now without misspelling):
`$hiringOrganization["logo"] = $logo;`

**Comment by typo3-itx** [comment]
You are right, must have misread your inital comment. We will fix that in the next update for good.

**Comment by typo3-itx** [comment]
Its fixed now, thanks again for reporting this.
