### ISSUE TITLE
Missing transOrigPointerField in TCA

### ISSUE THREAD

**Issue by derghostface** [typo3-itx/jobapplications#7]
In TYPO3 9.5 when you want to insert a record (contact, location, posting, ...) you cannot save it:
`SQL error: 'Unknown column 'l10n_parent' in 'field list'' (tx_jobapplications_domain_model_location:NEW5eb1258335ed6027431233)`

This only occurs if you have a blank db table. If you already have records in the table, the error does not occur.

The fix is to insert the `'transOrigPointerField' => 'l10n_parent'` in every TCA definition.

TYPO3 9.5.16
PHP 7.2.30

**Comment by typo3-itx** [comment]
Thanks for reporting this. This was a v9 incompatible migration for v10. It's added back in now.
