### ISSUE TITLE
Call to a member function toArray() on null

### ISSUE THREAD

**Issue by derghostface** [typo3-itx/jobapplications#8]
When saving a textmedia element with a new fal relation I get following error:

`Call to a member function toArray() on null in /typo3conf/ext/jobapplications/Classes/Utility/GoogleIndexingApiConnector.php line 92`

I added a check in \ITX\Jobapplications\Hooks\TCEmainHook::processDatamap_afterDatabaseOperations for the table "tx_jobapplications_domain_model_posting" to prevent this error.

Don't know whether this is the correct fix for it, but I can't image that it is necessary that this hook is processed after every database operation of every table.

**Comment by typo3-itx** [comment]
Yes you are correct. This was a forgotten if statement. Thanks for your help!
