### ISSUE TITLE
Issue with 0.9.8 und Image Upload in Content Elements

### ISSUE THREAD

**Issue by schorsch8878** [typo3-itx/jobapplications#9]
I have the following Issue with 0.9.8: If I insert an Image in a Content Element (Text with Image or others like News) Typo3 show an error message after saving the element.

![image001](https://user-images.githubusercontent.com/26795388/82198958-5517ea80-98fd-11ea-8034-d0ceb5c553a0.png)

**Comment by typo3-itx** [comment]
Yes this was a bug in the Indexing Connector. It's fixed now. Thanks for reporting
